# Site
repository: linkarzu/docker-jekyll-resume

favicon: images/favicon2.ico # (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Christian Arzu (linkarzu)
title: Senior monitoring engineer
# email: Your email (optional)
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://linkarzu.com 
website_title: My blog
# This website2 below doesnt work
# website2: youtube.com/@linkarzu 
# website2_title: YouTube

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: christianarzu
github_username:  linkarzu
youtube_username: "@linkarzu"
# twitter_username: jekyllrb
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Credly
  icon: fas fa-certificate #I updated the icon version in _sass/base.scss to v6.4.0
  url: https://www.credly.com/users/chrisjosuearzu/badges
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://res.cloudinary.com/daqwsgmx6/image/upload/v1683578753/Profile%20pics/linkedin.jpg
about_content: | # this will include new lines to allow paragraphs
  I like to learn about new stuff related to technology, not specific to a particular field. 
  Whether it's Linux, networking, virtualization, containerization, cloud services, web design, programming - you name it; 
  if it's something I can use in real life, I'm down for learning and applying it. 
  - Check out my: [Personal blog](https://linkarzu.com){:target="_blank"}
  - Check out my: [YouTube channel](https://www.youtube.com/@linkarzu){:target="_blank"}

# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

# To reduce space between elements I modified _sass/modern-resume-theme.scss
# In the file look for the modifiedRemSpaceSections comment
content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: left
        title: GoTo
        sub_title: Monitoring engineer
        caption: Sept 2022 - present <br> (1 year 6 months)
        link: https://www.goto.com
        quote:
        description: | # this will include new lines to allow paragraphs
          ```html
          - Manage official monitoring tools used across the company. 
          - Monitor SNMP, WMI devices, cloud infrastructure, synthetic tests, alert routing, and alert correlation.
          - Deploy and maintain necessary infrastructure either on the cloud or on-prem.          
          - Handle vendor contracts, and guide internal users on how to choose the best tool for the job.
          ```
      - layout: left
        title: GoTo
        sub_title: Site Reliability Engineer
        caption: Jul 2020 - Sept 2022 <br> (2 years 2 months)
        # link: https://www.goto.com
        quote:
        description: | # this will include new lines to allow paragraphs
          ```yaml
          - Worked in the NOC team ensuring uptime for all the different public-facing products. 
          - Monitor critical alerts across the company to avoid and fix potential issues. 
          - Incident management including status pages.
          - SSL certificate follow-up to avoid expired certs causing downtime.
          ```
      - layout: left
        title: GoTo
        sub_title: Field Engineer
        caption: May 2019 - July 2020 <br> (1 year 2 months)
        # link: https://www.goto.com
        quote:
        description: | # this will include new lines to allow paragraphs
          ```css
          - Deployed Jive’s VoIP cloud PBX for enterprise customers. 
          - Configure and troubleshoot various network devices. 
          - Routers, switches (segmentation of networks through VLANs), firewalls and SD-WAN appliances.
          ```
      - layout: left
        title: GoTo
        sub_title: Tier 2 tech support
        caption: Sept 2018 - May 2019 <br> (9 months)
        # link: https://www.goto.com
        quote:
        description: | # this will include new lines to allow paragraphs
          ```
          - Handled Jive VoIP customer care issues and T1 reps escalations.
          ```
      # - layout: left
      #   title: World Connection
      #   sub_title: Quality Analyst
      #   caption: Dec 2016 - Sept 2018 <br> (1 year 10 months)
      #   link: https://worldconnection.com
      #   quote:
      #   description: | # this will include new lines to allow paragraphs
      #     - Working for the website Sparefoot.com
      # - layout: left
      #   title: Telus International
      #   sub_title: Google tech support rep
      #   caption: Sept 2014 - May 2015 <br> (9 months)
      #   link: https://www.telusinternational.com
      #   quote:
      #   description: | # this will include new lines to allow paragraphs
      #     - Google Apps for Work in the Email migrations department
  - title: Education
    layout: list
    content:
      - layout: left
        title: Technical Certifications
        sub_title: Certifications
        caption: 2018 - Present
        quote: 
        description: | # this will include new lines to allow paragraphs
          ```json
          - My latest certification is "CKA: Certified Kubernetes Administrator"
          - But over the years, i've acquired other certs from different vendors (Cisco, Juniper, Akamai, etc).
          ```
          - Links to some of my certifications:
            - [CKA: Certified Kubernetes Administrator](https://www.credly.com/badges/5c50c596-19c8-4144-aa34-15df59a09c06){:target="_blank"}
            - [CCNP Routing and Switching](https://www.credly.com/badges/e366f67f-effd-4a83-b3f4-5b3e227965a3){:target="_blank"}
          - [My Credly profile](https://www.credly.com/users/chrisjosuearzu/badges){:target="_blank"}
      - layout: left
        title: Universidad Mariano Gálvez
        sub_title: Systems engineering
        caption: 2021 - 2025
        quote: 
        description: | # this will include new lines to allow paragraphs
          ```
          - Learning programming languages like C++, Java and C#.
          - Data structures in C# (linked lists, binary search trees, etc).
          ```
      - layout: left
        title: Universidad San Carlos
        sub_title: Systems engineering
        caption: 2007 - 2009
        quote: 
        description: | # this will include new lines to allow paragraphs
          ```
          - Incomplete studies, I was younger and wanted to live life :wink:
          ```
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      ```
      - My journey in the IT world started when I decided to get my Cisco CCNA certification back in 2018, but then I realized that networking is just a small part of the landscape, so I've been trying to catch up to new technologies ever since.
      - I adapt quickly and connect the dots to understand how things work. If I don't know an answer, I'm not going to pretend I know and give you false information, I'll tell you to give me some time and come back with something useful.
      - I love taking notes, let's say for example I'm learning to deploy WordPress on a docker container in a GCP VM, I'll document the whole process in case I need to re-do it. 
        - I used to manage my notes in Google Docs but it's too slow to load, so migrated all my notes to Obsidian, so now everything is handled as markdown files and automatically uploaded to my private GitHub repo.
      ```

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
